# Generated by Django 4.0.4 on 2022-05-21 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('identidad', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('raza', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra')], max_length=255)),
                ('esterilizado', models.BooleanField(default=False)),
                ('peso', models.FloatField()),
                ('qr', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
    ]
