# Generated by Django 4.0.4 on 2022-05-29 01:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('detalles', models.CharField(max_length=500, verbose_name='Detalles')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Nombre')),
                ('identidad', models.CharField(max_length=255, unique=True, verbose_name='Identidad')),
                ('color', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Color')),
                ('raza', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Raza')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra')], max_length=255, verbose_name='Sexo')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado')),
                ('peso', models.FloatField(verbose_name='Peso en LB')),
                ('qr', models.CharField(blank=True, max_length=900, null=True, verbose_name='Código Qr')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo')),
                ('texto', models.CharField(max_length=900, verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad (opcional)')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[\\+]?[\\d]{5,15}$', 'Formato incorrecto')], verbose_name='Teléfono')),
                ('ci', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Carnet')),
                ('veterinario', models.BooleanField(default=True, verbose_name='Es veterinario')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
            ],
        ),
    ]
