# Generated by Django 4.0.4 on 2022-05-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='organizacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.FloatField(verbose_name='Peso en KG'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='raza',
            field=models.CharField(max_length=255, verbose_name='Raza'),
        ),
    ]
