# Generated by Django 4.0.4 on 2022-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='date_creation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
