# Generated by Django 4.0.4 on 2022-05-26 16:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ficha_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad (opcional)')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('veterinario', models.BooleanField(default=True, verbose_name='Es veterinario')),
            ],
        ),
        migrations.AlterField(
            model_name='ficha',
            name='color',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='foto',
            field=models.ImageField(upload_to='fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='identidad',
            field=models.CharField(max_length=255, unique=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.FloatField(verbose_name='Peso en LB'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='qr',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Código Qr'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='raza',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')], verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sexo',
            field=models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra')], max_length=255, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visitante', verbose_name='Visitante')),
            ],
        ),
    ]
