# Generated by Django 4.0.4 on 2022-05-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visita_organizacion_alter_ficha_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='foto',
            field=models.ImageField(default='', upload_to='fotos/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
