# Generated by Django 4.0.4 on 2022-05-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_informacion_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='identidad',
        ),
    ]
