# Generated by Django 4.0.4 on 2022-05-26 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitante_alter_ficha_color_alter_ficha_esterilizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('detalles', models.CharField(max_length=500, verbose_name='Detalles')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=900, verbose_name='Texto')),
            ],
        ),
    ]
