# Generated by Django 4.0.4 on 2022-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
    ]
