# Generated by Django 4.0.4 on 2022-05-29 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\+]?[\\d]{5,15}$', 'Formato incorrecto')], verbose_name='Teléfono')),
                ('link', models.URLField(max_length=900, verbose_name='Link de contacto')),
            ],
        ),
    ]
