# Generated by Django 4.0.4 on 2022-05-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_asociado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociado',
            name='apellido',
        ),
    ]
