# Generated by Django 4.0.4 on 2022-05-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ficha_enfermedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=900, verbose_name='Descripción')),
            ],
        ),
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enfermedades o lesiones'),
        ),
    ]
