# Generated by Django 4.0.4 on 2022-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enfermedad_alter_ficha_enfermedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación (opcional)')),
                ('caracteristicas', models.CharField(max_length=255, verbose_name='Características del animal')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Evidencia (foto)')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
