# Generated by Django 4.0.4 on 2022-05-31 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.utcnow, verbose_name='Fecha de vacunación')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('fecha_siguiente', models.DateField(verbose_name='Fecha de la próxima vacuna')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficha', verbose_name='Ficha a vacunar')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
