# Generated by Django 4.0.4 on 2022-05-31 10:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vacuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.CharField(choices=[('f1', 'Facultad 1'), ('f2', 'Facultad 3'), ('f3', 'Facultad 3'), ('f4', 'Facultad 4'), ('fte', 'Facultad FTE'), ('citec', 'Facultad CITEC'), ('otro', 'Otro')], max_length=100, verbose_name='Facultad o área'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Debe ser positivo')], verbose_name='Peso en KG'),
        ),
        migrations.CreateModel(
            name='Desparasitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.utcnow, verbose_name='Fecha de vacunación')),
                ('tipo', models.CharField(choices=[('externa', 'Desparasitación externa'), ('interna', 'Desparasitación interna')], max_length=100, verbose_name='Tipo')),
                ('peso', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Debe ser positivo')], verbose_name='Peso')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficha', verbose_name='Ficha a desparasitar')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
