# Generated by Django 4.0.4 on 2022-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contacto_area_alter_ficha_peso_desparasitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
