# Generated by Django 4.0.4 on 2022-06-25 05:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_denuncia_foto_alter_denuncia_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='tipo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Abandono'), (2, 'Mal estado físico'), (3, 'Hacinamiento'), (4, 'Violencia física'), (5, 'Causar la muerte')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
