# Generated by Django 4.0.4 on 2022-06-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_denuncia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de denuncia'),
        ),
    ]
