# Generated by Django 4.0.4 on 2022-06-25 23:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_denuncia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.CharField(choices=[('f1', 'Facultad 1'), ('f2', 'Facultad 2'), ('f3', 'Facultad 3'), ('f4', 'Facultad 4'), ('fte', 'Facultad FTE'), ('citec', 'Facultad CITEC'), ('otro', 'Otro')], max_length=100, verbose_name='Facultad o área'),
        ),
        migrations.AlterField(
            model_name='desparasitacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Fecha de desparasitación'),
        ),
        migrations.AlterField(
            model_name='desparasitacion',
            name='peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Debe ser positivo')], verbose_name='Peso (kG)'),
        ),
        migrations.AlterField(
            model_name='desparasitacion',
            name='tipo',
            field=models.CharField(choices=[('externa', 'Externa'), ('interna', 'Interna'), ('ambas', 'Externa e Interna')], max_length=100, verbose_name='Tipo'),
        ),
    ]
