# Generated by Django 4.0.4 on 2022-06-29 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_medicamento_cantidad_alter_contacto_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('1', 'Campaña de desparasitación'), ('2', 'Campaña de vacunación'), ('3', 'Campaña de esterilización'), ('4', 'Feria de adopciones')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='ci',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'El carnet debe ser de 11 dígitos')], verbose_name='Carnet'),
        ),
    ]
